### PR TITLE
Proper initialisation on ICLIST list of components

### LINKED ISSUE #32: Undefined ICLIST encountered
When upgrading from 16.8.0-rc2 to 16.8.0-rc3, I get the following message:
```
2016/09/13-18:59:22 [INFO] new profile arrived, examining...
updated /var/lib/ccm/profile.1700/ccm-active-profile.1700-4114529
2016/09/13-18:59:22 [INFO] Undefined ICLIST encountered. Report this to the developers (including the templates under /var/lib/ccm and any logs): old cid 1699 new cid 1700
2016/09/13-18:59:22 [INFO] new (and changed) profile detected
```
It seems to have started after the upgrade to 16.8.0-rc2 and before the upgrade to rc3. The problem may have been triggered by the HW template updates (CPU/NIC) and not be related to `ncm-cdispd` 16.8 as it also seems to affect machines running older versions (16.2 for example).

This needs to be investigated before [16.8.0](https://github.com/quattor/release/issues/259) release.

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #32

### CODE REVIEW

**Comment by stdweird** [comment]
Not tested, in particular the tainted mode

**Comment by ned21** [comment]
LGTM. How do you want to do the testing? Can we get jenkins to generate a rpm so sites can just install it on a few test machines?

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
@ned21 i was going to deploy this on our systems :smile: (and jenkins now also makes rpms)

**Comment by ned21** [comment]
I installed the rpm on a 16.6 host and saw it run without issue

**Comment by stdweird** [comment]
same here tested on a few systems, rolling it out to more systems soon

**Comment by jouvin** [comment]
I had no time to test it on real machines yet... but the code changes LGTM. Thanks @stdweird for the cleanup (and apologies for the nasty typo I am probably responsible for...).

**Comment by jouvin** [comment]
I managed to (easily) reproduce the problem with 16.8.0. I'll try to validate the the proposed fix asap...

**Comment by stdweird** [comment]
@jouvin thx, jenkins has rpms https://jenkins1.ugent.be/job/ncm-cdispd-pr-builder/27/org.quattor.daemon$ncm-cdispd/ you can use

**Comment by jouvin** [comment]
I tested this PR and was able to assess that it does fix the issue with undefined ICLIST. For the record, the issue was originally trigged and then reproduced by adding:
```
"type": "deprecated"
```
to one of the interface properties.

As for me, the PR is ready to be merged.

**Pull request merged**
