### PR TITLE
ncm-cdispd: factor out main script code in Main module to allow unittests

### LINKED ISSUE #50: Postinstall script restarts service, which re-runs ncm-ncd part-way through an upgrade.
`ncm-cdispd` is restarted by the post-install script during an upgrade, at the point at which the restart happens the system is in an inconsistent state, where some packages have not yet been upgraded — cue scary "bad Perl code" warnings.

Here are sanitised logs for [sl6x](https://gist.github.com/jrha/9801ea3bff1fbdaa37ae611661aa9da6) and [sl7x](https://gist.github.com/jrha/dac64f4427dee1601ac4243a892b9d6c) VMs showing the problem.

As mentioned in quattor/release#297.

### PR DESCRIPTION
**Pull request by stdweird**
This PR is mainly moving code and splitting out the main loop + fixes required for #50

Fixes #50

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha i'm going to test this, but have no clue what milestone to set

**Comment by jrha** [comment]
This should be merged into 17.4, I'll backport it to 17.3.1

**Comment by stdweird** [comment]
@jrha fix looks good
thanks to @wdpypere doing the testing and initial reporting

**Comment by wdpypere** [comment]
👍

**Pull request merged**
