### PR TITLE
Make the RPMs more rpmlint compliant.

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
warnings left
```
ncm-cdispd.noarch: W: non-standard-group Quattor
ncm-cdispd.noarch: W: non-standard-dir-in-usr quattor
ncm-cdispd.noarch: W: service-default-enabled /etc/init.d/ncm-cdispd
1 packages and 0 specfiles checked; 0 errors, 3 warnings.
```

**Comment by ned21** [comment]
64dd188 could do with a bit more explanation. Is the change in lock file location dictated by rpm lint? What about the additional unit test - does that deserve its own commit?

**Comment by stdweird** [comment]
the unittest is a standard i copied from soem other repo, because there were some many pod warnings (not that they were related to the invalid pod code, but i saw no point in removing it again). a separate commit, if you insist, i could make one.

the lockfile triggers the subsys error below. the original code does not create the basedir `/var/lock/quattor` (we have seen error logged in post AII due to that). and the pom.xml causes rpmlint to complain that locks should be in subsys. so i just moved the lockfile location to subsys (as it is in `cdp-listend`).

for future reference, the original rpmlint output
```
ncm-cdispd.noarch: W: non-standard-group Quattor
ncm-cdispd.noarch: E: no-changelogname-tag
ncm-cdispd.noarch: W: invalid-license c
ncm-cdispd.noarch: W: invalid-license Quattor
ncm-cdispd.noarch: W: invalid-url URL: http://quattor.org/cfg-modules/ncm-cdispd/ HTTP Error 404: Not Found
ncm-cdispd.noarch: E: script-without-shebang /usr/lib/perl/CDISPD/Utils.pm
ncm-cdispd.noarch: E: script-without-shebang /usr/lib/perl/CDISPD/Application.pm
ncm-cdispd.noarch: W: no-manual-page-for-binary ncm-cdispd
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Application.pm perl(CAF::Application)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Utils.pm perl(LC::Exception)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Application.pm perl(LC::Exception)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Utils.pm perl(Exporter)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Application.pm perl(Exporter)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Utils.pm perl(POSIX)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Utils.pm perl(strict)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Application.pm perl(strict)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Application.pm perl(CAF::Reporter)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Utils.pm perl(EDG::WP4::CCM::CacheManager)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Utils.pm perl(EDG::WP4::CCM::Path)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Application.pm perl(CAF::Object)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Utils.pm perl(constant)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Application.pm perl(constant)
ncm-cdispd.noarch: W: doc-file-dependency /usr/lib/perl/CDISPD/Application.pm perl(CAF::Process)
ncm-cdispd.noarch: W: non-standard-dir-in-usr quattor
ncm-cdispd.noarch: E: invalid-locale-man-dir /usr/share/man/man8/man8/CDISPD::Application.8.gz
ncm-cdispd.noarch: W: file-not-in-%lang /usr/share/man/man8/man8/CDISPD::Application.8.gz
ncm-cdispd.noarch: E: invalid-locale-man-dir /usr/share/man/man8/man8/CDISPD::Utils.8.gz
ncm-cdispd.noarch: W: file-not-in-%lang /usr/share/man/man8/man8/CDISPD::Utils.8.gz
ncm-cdispd.noarch: E: invalid-locale-man-dir /usr/share/man/man8/man8/ncm-cdispd.8.gz
ncm-cdispd.noarch: W: file-not-in-%lang /usr/share/man/man8/man8/ncm-cdispd.8.gz
ncm-cdispd.noarch: W: service-default-enabled /etc/init.d/ncm-cdispd
ncm-cdispd.noarch: E: subsys-not-used /etc/init.d/ncm-cdispd
```

**Comment by ned21** [comment]
A separate commit would be good please. Please also put the note about the lockfile into the commit log.

**Comment by stdweird** [comment]
@ned21 i split the last commit

**Pull request merged**
