### PR TITLE
Only touch statefiles for active, to be dispatched components

### PR DESCRIPTION
**Pull request by stdweird**
Partial solution to #35 
Requires #34

### CODE REVIEW

**Comment by stdweird** [comment]
@ned21 @jouvin does not cleanup any leftovers from previous ncm-cdispd starts. 
rpm at https://jenkins1.ugent.be/job/ncm-cdispd-pr-builder/28/org.quattor.daemon$ncm-cdispd/

**Comment by ned21** [comment]
LGTM

**Comment by stdweird** [comment]
@ned21 rebased

**Comment by ned21** [comment]
@jrha Any chance of an official 16.8.1 release of ncm-cdispd to fix this bug please?

**Comment by jrha** [comment]
Can do!

**Pull request merged**
