### PR TITLE
add unitfile for ncm-cdispd, remove initscripts/chkconfig support

### LINKED ISSUE #56: ncm-cdispd needs a systemd unit file

### PR DESCRIPTION
**Pull request by stdweird**
Add unitfile for ncm-cdispd.

Possible issue: the configfile options "--quiet/-D" should not be set; and pidfile and logfile options are ignored

Resolves #56.

### CODE REVIEW

**Comment by jouvin** [comment]
@stdweird I open a PR on your PR to remove references to `chkconfig` that requires to define `chkconfig` as dependency for `ncm-cdispd`, as it is a source of problem on EL9. This breaks the compatibility with EL6 but it is also the case in `cdp-listend` (https://github.com/quattor/cdp-listend/pull/33).

I let you fix the unit test problems that are not introduced by my changes.

**Comment by jouvin** [comment]
@stdweird please could you merge my PR to your branch so that we have a branch with everything. This is really required for EL9 support.

**Comment by ned21** [comment]
Not sure it's completely accurate but adding the backwards incompatible label to highlight in the release notes that this drops EL6 support.

**Comment by jouvin** [comment]
@stdweird can we fix the unit tests? I've the feeling the error is caused by your changes but I have not checked carefully... :-)

**Comment by jrha** [comment]
Rebased.

**Comment by jrha** [comment]
Looks like the double test counting may still be an issue.

**Review by jrha — APPROVED** [review]

**Comment by jrha** [comment]
I've removed the commit changing the way the unit tests were run as it isn't relevant to this change and it looks like it needs at least newer build-tools to pass.

**Pull request merged**
