### PR TITLE
restore the old ICLIST on ncm-ncd failure

### LINKED ISSUE #22: restore old ICLIST on failure
step 0: initialisation
- CID 1 , components: X 
- NEWCFG == OLDCFG
- ICLIST = X

step 1: new profile
- OLDCID 1, components: X
- NEWCID 2, components: X,Y
- ICLIST X,Y
ncm-ncd --co X Y fails (for whatever reason)
there is no transition of NEWCFG->OLDCFG

step 2. newprofile (or option 2b old profile, ie with same checksum as CID 1)
- OLDCID 1, components: X
- NEWCID 3, components: X
- ICLIST X,Y (not reset since previous one failed and/or because checksum is the same as in e.g. option 2b)
ncm-ncd --co X,Y fails (due to no Y component in NEWCFG)

there is no recovery possible (except restarting ncm-cdispd)
solution: restore ICLIST from step 0 if there's a failure in step 1.

problem: the `launch_ncd` sub has the following
```
# At this point, ICLIST should contain only components present in the last profile received.
# The only case where a component may be in the list without being part of the configuration
# is the following:          
#   - Profile n is deployed succesfully (ncm-ncd returns a success)
#   - Profile n+1 add a new component X that fails (reference config to compare next profile with remains n)
#   - Profile n+2 remove component X but the profile comparison occurs between n and n+2 (because 
#     X failed with profile N+1) and thus X removal is not detected.
# As a result, X remains on the list of component to run. This should be harmless as ncm-ncd will ignore it.
# This is probably rare enough to avoid complex processing to handle this in ncm-dispd.
```
for some reason, it assumes that `ncm-ncd` simply ignores undefined components.
i also do not understand why this whole ICLIST thing is needed, and we don't simply run `ncm-ncd --all`

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #22

### CODE REVIEW

**Comment by stdweird** [comment]
@jouvin i'm not an ncm-cdispd expert, and i'm clearly missing some background, but this fixes our problem.

**Comment by jrha** [comment]
LGTM, what is the ICLIST?

**Comment by stdweird** [comment]
it's the list of components to be invoked

**Comment by jouvin** [comment]
I am not sure to agree with the change, please let me some time to review it... ICLIST is critical to ensure that failed components are retried the next time a profile is received: it used to be the intent but not the case and this was leaving systems half configured after a config module failure.
I try to have a look this evening.

**Comment by jouvin** [comment]
@stdweird I looked in more details to your suggested mod and it seems ok to me. Have you carefully checked what happens it the first run of components after the initial startup fails to ensure that we don't have an undefined variable left somewhere?

**Comment by stdweird** [comment]
@jouvin the initial `ICLIST` is initialised at https://github.com/quattor/ncm-cdispd/blob/master/src/main/scripts/ncm-cdispd#L717, that looks clean enough to me and well before any of the chnages in this PR come into play.

**Pull request merged**
