### PR TITLE
ncm-cdispd: report sleep when no updated profile found with debug 1

### LINKED ISSUE #45: 16.10.0-rc1: verbose too verbose!
With verbose now being the default logging level, it is necessary to degrade the message ` no new profile found, sleeping` to debug1. Else, the log file is full of this useless message (1 every 2 minutes).

IMO, showstopper for [16.10.0-rc1](https://github.com/quattor/release/issues/266).

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #45

### CODE REVIEW

**Comment by stdweird** [comment]
Untested

**Comment by ned21** [comment]
LGTM. Any volunteers to test it? Is this a blocker for 16.10?

**Comment by jouvin** [comment]
Yes, this is an almost-blocker, see #45. You can fill up your log very quickly... I tested it and it works exactly as expected. Here is the output with this patch from `ncm-cdispd.log`:
```
2016/11/07-14:08:15 [INFO] ncm-ncd finished with status: 0 (ec 0, all configuration modules ran successfully)

2016/11/07-14:12:15 [INFO] new profile arrived, examining...
updated /var/lib/ccm/profile.22/ccm-active-profile.22-636045
2016/11/07-14:12:15 [VERB] new profile detected: cid=22
2016/11/07-14:12:15 [INFO] new profile has same checksum as old one, no NCM run
```
Without the patch you'll have got 3 (useless) lines `no new profile found, sleeping` between the end of the `ncm-ncd` run and the detection of the new profile.

I am in favor of merging this PR.

**Comment by ned21** [comment]
@jouvin Cool - please go ahead and merge!

**Pull request merged**
